sudo: true
language: python
dist: xenial

matrix:
    fast_finish: true
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
    allow_failures:
        - python: 3.7

cache: pip

git:
    depth: false

install:
    - pip install --upgrade pip
    - pip install --upgrade tox

script: tox
