sudo: false
language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

cache: pip

env:
    global:
        - STAGPY_NO_CONFIG=True

install:
    - pip install -q "pytest>=3.3"
    - pip install -q .

script: pytest
