sudo: false
language: python

matrix:
    include:
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7-dev
          env: TOXENV=py37

cache: pip

git:
    depth: false

install:
    - pip install --upgrade tox

script: tox
